### ISSUE TITLE
1.Logo Change 2.Add Visuals 3. Create a separate form named 'For Collboration' 4. Change with more eye-catchy icons

### ISSUE THREAD

**Issue by Rit00** [Consult-Strategy/Consult-Strategy.github.io#10]

**Comment by ayan-biswas0412** [comment]
Logo Change 2.Add Visuals 3. Create a separate form named 'For Collaboration' 4. Change with more eye-catchy icons 

@ankit98040  are you available Please take this and give me an update before 6 PM you only have to change the logo of the OYO and the logo is attached 
![oyo-logo](https://user-images.githubusercontent.com/52851184/84364076-43b8ba00-abed-11ea-8bd3-4d22111c980a.png)

**Comment by ankit98040** [comment]
logo changed and also in the customer review part, added (&) between Consult & Strategy. 

for the collaboration part, I would need the survey monkey form link. it would be helpful then

**Comment by ayan-biswas0412** [comment]
@ankit98040 please give link of your pull request here

**Comment by ankit98040** [comment]
https://github.com/Consult-Strategy/Consult-Strategy.github.io/pull/14

**Comment by ayan-biswas0412** [comment]
```
<form action="https://formspree.io/xoqkweeg" method="POST">
  <input type="text" name="name">
  <input type="email" name="_replyto">
  <input type="submit" value="Send">
</form>
```
Use this instead of the surveymonkey

**Comment by ayan-biswas0412** [comment]
done by @ankit98040 reviewd by @ayan-biswas0412 via PR #14

**Comment by ankit98040** [comment]
<img width="1436" alt="Screenshot 2020-06-11 at 4 32 50 PM" src="https://user-images.githubusercontent.com/59945244/84378128-49b89600-ac01-11ea-9a9f-cecae655b808.png">


https://github.com/Consult-Strategy/Consult-Strategy.github.io/pull/17
