### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by Rit00** [Consult-Strategy/Consult-Strategy.github.io#11]
<form action="https://formspree.io/xoqkweeg" method="POST">
  <input type="text" name="name">
  <input type="email" name="_replyto">
  <input type="submit" value="Send">
</form>

**Comment by ayan-biswas0412** [comment]
```
<form action="https://formspree.io/xoqkweeg" method="POST">
  <input type="text" name="name">
  <input type="email" name="_replyto">
  <input type="submit" value="Send">
</form>
```
Use this instead of the surveymonkey

@ankit98040 please take this issue and make your chages as you previously done , give update me before 7 PM here

**Comment by ayan-biswas0412** [comment]
@ankit98040 always pull the code from the master then do like same before

**Comment by Rit00** [comment]
No survey monkey will be there this is for our customers which will be displayed in the webpage before internship form

**Comment by Rit00** [comment]
@ayan-biswas0412 @ankit98040 take a note.
This form will be in the webpage for our clients.Survey monkey is for internships /student application

**Comment by ayan-biswas0412** [comment]
This is done also
