### ISSUE TITLE
Change in Our Client-in comment of oyo"Consult & Strategy" include '&'

### ISSUE THREAD

**Issue by Rit00** [Consult-Strategy/Consult-Strategy.github.io#13]
Change in Our Client-in comment of oyo"Consult & Strategy" include '&' 

Dear @ankit98040 please make this also

**Comment by ankit98040** [comment]
Okay sir

**Comment by ayan-biswas0412** [comment]
Done by @ankit98040 reviewd by @ayan-biswas0412  #14
