### ISSUE TITLE
Visual,Display,Animation in Professional way

### ISSUE THREAD

**Issue by Rit00** [Consult-Strategy/Consult-Strategy.github.io#19]
@ayan-biswas0412
1. take care of this.Change a few icons specially for Analytics.
2. Incline the text content in a beautiful manner if possible change fonts.Make it classic
3.Add the built in form i sent to you yesterday that would be in the website.

**Comment by ayan-biswas0412** [comment]
@Rit00 now our new site is live and it is not needed now as the previous site is not available so i am closing this
