### ISSUE TITLE
New Templates 

### ISSUE THREAD

**Issue by ayan-biswas0412** [Consult-Strategy/Consult-Strategy.github.io#20]
https://bootstrapmade.com/demo/Tempo/
https://bootstrapmade.com/demo/OnePage/
https://bootstrapmade.com/demo/KnightOne/
https://bootstrapmade.com/demo/Gp/
https://bootstrapmade.com/demo/eNno/
https://bootstrapmade.com/demo/Day/
https://bootstrapmade.com/demo/Knight/
https://bootstrapmade.com/demo/Flexor/

@Rit00 Please review this and there are many other templates in https://bootstrapmade.com/bootstrap-business-templates/

Please also check mobile views also there is an option available under preview 

I will update some templates here and respond here then I will start the work

**Comment by Rit00** [comment]
Its good comment your thoughts
https://bootstrapmade.com/demo/Day/

**Comment by Rit00** [comment]
@ayan-biswas0412  can we add the video here instead of picture?
![Screenshot_20200611-221414_Chrome](https://user-images.githubusercontent.com/60076002/84415818-f52d0f00-ac30-11ea-9d53-c58b196cae8d.jpg)

**Comment by Rit00** [comment]
Direct call me please sometime I may miss email

**Comment by Rit00** [comment]
I will be active for full time untill its getting done!
Call me when you need any help or comment

**Comment by Rit00** [comment]
@ayan-biswas0412 have a look and let me know when you will be doing tomorrow so that I will make plan accordingly

**Comment by ayan-biswas0412** [comment]
I will do an initial commit today late night, **take sleep** you will get an initial version ready by tomorrow noon and we will have a call tomorrow 3 PM

**Comment by Rit00** [comment]
Thanks for the update,Good night.

Regards,
Ritavash Hazra
Jadavpur University,Kolkata
Phone-7031039385
visit-https://ritavashhazra.wixsite.com/profile

**Comment by ayan-biswas0412** [comment]
This is now done
